### PR TITLE
Dilernia tables patch

### PR DESCRIPTION
**Pull request by dilernia**
Patched the functions producing flextable objects to fix column width issue when knitting to Word. Did so by adding autofit() and fit_to_width() calls at the end of the functions that return flextable objects. This adds redundancy to the code, but minimized / prevented changes to the other functions in the package.

### CODE REVIEW

**Comment by ian-curtis** [comment]
Hey! Thank you for this!

Do you know if this is a widespread issue across all tables or just those in the files you edited here? I ask because I wonder if your edits would be better placed in `R/utils.R` in the `finalize_tbl()` function. The function currently runs

```
...
flextable::autofit() %>%
flextable::fit_to_width(6) %>%
flextable::set_caption(...)
```
at the very end but I wonder if it's not working due to the caption being the last step rather than before the auto fitting, if that makes sense.

Based on your testing, would it make more sense to convert your edits here into 

```
...
flextable::set_caption(...) %>%
flextable::autofit() %>%
flextable::fit_to_width(6) # or 7.5
```
and put it in the `finalize_tbl()` function?

**Comment by dilernia** [comment]
I believe it was all tables that have wide enough columns when knitting to
Word (I reproduced the issue with a couple data sets).

Updating the finalize_tbl() function would be the most efficient route I
think. I actually tried going this route in my forked repo of gvsu215
because I suspect that is right - setting the caption could be undoing the
fitting of the table. I can't remember where exactly, but updating
the finalize_tbl() function in this way seemed to cause separate issues to
pop-up when I updated it throughout the package, so I patched the functions
that output tables. Whatever solution you find works easiest is great
though!

Andrew

**Comment by ian-curtis** [comment]
After some testing, I believe the issue some from `set_header_labels()` coming after the original fitting functions in `finalize_tbl()`. I'm going to try to merge your pull request and use it as a starting point to consolidate some code. I'm thinking a new utility function called `fit_tbl()` that can easily be run at any time by anyone and can also be called at the end of every one of the functions you edited here.

**Comment by dilernia** [comment]
Sounds good, thanks Ian! If you'd like to chat about anything or have me
test anything out feel free to let me know.

Andrew

**Pull request merged**
